//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPM.API.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Disease_Solution
    {
        [Display(Name = "Disease Solution")]
        public string DSol_ID { get; set; }
        [Display(Name = "Disease")]
        public string D_ID { get; set; }
        [Display(Name = "Solution")]
        public string Sol_ID { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual Solution Solution { get; set; }
    }
}
