//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPM.API.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Disease_Symptom
    {
        [Display(Name = "Disease Symptom")]
        public string DS_ID { get; set; }
        [Display(Name = "Disease")]
        public string D_ID { get; set; }
        [Display(Name = "Symtom")]
        public string S_ID { get; set; }
        [Display(Name = "Part")]
        public string Part_ID { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual Part Part { get; set; }
        public virtual Symptom Symptom { get; set; }
    }
}
