//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPM.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Management
    {
        public string ManagementID { get; set; }
        public Nullable<System.DateTime> Harvest_Date { get; set; }
        public Nullable<decimal> Bunches { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> Toppled_Plants { get; set; }
        public Nullable<decimal> Weavils_Noticed { get; set; }
        public string Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
